server:
  port: 10600
spring:
  redis:
    host: 192.168.126.138
    port: 6379
    password: 1234
  profiles:
    include: shardingsphere
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.126.138
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual  #手动应答

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.liu.gmall.order.entity;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  sentinel:
    enabled: true
gmall:
  threadpool:
    corePoolSize: 8
    maximumPoolSize: 16
    keepAliveTime: 30
    workQueueSize: 10