server:
  port: 10500
spring:
  redis:
    host: 192.168.126.138
    port: 6379
    password: 1234
  main:
    allow-bean-definition-overriding: true
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
